behaviors:
  BrawlOnes:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 16384
      learning_rate: 0.0002
      beta: 0.01
      epsilon: 0.2
      lambd: 0.96
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
      memory:
        sequence_length: 256
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 1000000000
    time_horizon: 1024
    summary_freq: 8192
    self_play:
      window: 30
      play_against_latest_model_ratio: 0.6
      save_steps: 100000
      swap_steps: 25000
      team_change: 400000
